export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const verifyConstant = {
  EMAIL_REQUEST: "EMAIL_REQUEST",
  EMAIL_SUCCESS: "EMAIL_SUCCESS",
  EMAIL_FAILURE: "EMAIL_FAILURE",
  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_FAILURE: "VERIFY_FAILURE",
};

export const cartConstant = {
  CART_REQUEST: "CART_REQUEST",
  CART_SUCCESS: "CART_SUCCESS",
  CART_FAILURE: "CART_FAILURE",
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  REMOVE_CART_REQUEST: "REMOVE_CART_REQUEST",
  REMOVE_CART_SUCCESS: "REMOVE_CART_SUCCESS",
  REMOVE_CART_FAILURE: "REMOVE_CART_FAILURE",
};

export const categoryConstant = {
  CATEGORY_REQUEST: "CATEGORY_REQUEST",
  CATEGORY_SUCCESS: "CATEGORY_SUCCESS",
  CATEGORY_FAILURE: "CATEGORY_FAILURE",
};

export const addressConstant = {
  ADDRESS_REQUEST: "ADDRESS_REQUEST",
  ADDRESS_SUCCESS: "ADDRESS_SUCCESS",
  ADDRESS_FAILURE: "ADDRESS_FAILURE",
};

export const courierConstant = {
  PATHAO_FEE_REQUEST: "PATHAO_FEE_REQUEST",
  PATHAO_FEE_SUCCESS: "PATHAO_FEE_SUCCESS",
  PATHAO_FEE_FAILURE: "PATHAO_FEE_FAILURE",
  CITY_REQUEST: "CITY_REQUEST",
  CITY_SUCCESS: "CITY_SUCCESS",
  CITY_FAILURE: "CITY_FAILURE",
  ZONE_REQUEST: "ZONE_REQUEST",
  ZONE_SUCCESS: "ZONE_SUCCESS",
  ZONE_FAILURE: "ZONE_FAILURE",
  AREA_REQUEST: "AREA_REQUEST",
  AREA_SUCCESS: "AREA_SUCCESS",
  AREA_FAILURE: "AREA_FAILURE",
};

export const orderConstant = {
  ORDER_REQUEST: "ORDER_REQUEST",
  ORDER_SUCCESS: "ORDER_SUCCESS",
  ORDER_FAILURE: "ORDER_FAILURE",
};
